# Generated by Django 4.2.5 on 2023-09-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_replies_alter_message_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='replies',
            new_name='replied_to',
        ),
    ]
